/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package posyandu;
import java.sql.*; 
import java.text.DateFormat; 
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel; 
import koneksi.koneksi; 

/**
 *
 * @author Adji
 */
public class pendaftaran_balita extends javax.swing.JFrame {
private Connection conn = new koneksi().connect();
private DefaultTableModel tabmode;
    /**
     * Creates new form pendaftaran_balita
     */
    public pendaftaran_balita() {
        initComponents();
        kosong();
        aktif();
        datatable();
    }
     protected void aktif(){
    idblt.requestFocus();
    tgllahir.setDate(null);
    }
     protected void kosong (){
    idblt.setText("");
    nmanak.setText("");
    buttonGroup1.clearSelection();
    nmayah.setText("");
    nmibu.setText("");
    tgllahir.setDate(null);
    beratbadan.setText("");
    usia.setText("");
    panjangbadan.setText("");
    rt.setText("");
    rw.setText("");
    almt.setText("");
    }
     
     public void removeTable(){
        try{
            for(int t=tabmode.getRowCount();t>0;t--) {tabmode.removeRow(0);}
        }catch(Exception ex) {System.out.println(ex);
}
    } 
     
     protected void datatable(){
        removeTable();
        int jumdata=0;
    Object[]Baris ={"idbalita","nama anak","jenis kelamin","nama ayah","nama ibu","tanggal lahir","Usia","berat badan","panjang badan","rt","rw","alamat"};
    tabmode = new DefaultTableModel(null,Baris);
    tabledatabalita.setModel(tabmode);
    String sql ="select*from pendaftaran_balita";
    
    try{
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){
                String idbalita = hasil.getString("idbalita");
                String nama_anak = hasil.getString("nama_anak");
                String jenis_kelamin = hasil.getString("jenis_kelamin");
                String nama_ayah = hasil.getString("nama_ayah");
                String nama_ibu = hasil.getString("nama_ibu");
                String tanggal_lahir = hasil.getString("tanggal_lahir");
                String usia = hasil.getString("usia");
                String berat_badan = hasil.getString("berat_badan");
                String panjang_badan = hasil.getString("panjang_badan");
                String rt = hasil.getString("rt");
                String rw = hasil.getString("rw");
                String alamat_lengkap = hasil.getString("alamat_lengkap");
                
                String [] data = {idbalita,nama_anak,jenis_kelamin,nama_ayah,nama_ibu,tanggal_lahir,usia,berat_badan,panjang_badan,rt,rw,alamat_lengkap};
                tabmode.addRow(data);
                jumdata=jumdata+1;
            }
        }catch (SQLException sqle) {
            jumdata=0;
        JOptionPane.showMessageDialog(null,"Data gagal masuk ke tabel" +sqle);
    }
    lblJum.setText(jumdata+ "Data");
}
     
      protected void autonumber(){ 
        try{ 
            String sql = "SELECT idbalita FROM pendaftaran_balita order by idbalita asc";
            Statement stat = conn.createStatement();
            ResultSet rs=stat.executeQuery(sql);
            idblt.setText ("IN0001");
             while(rs.next()){ 
                 String idbalita = rs.getString("idbalita").substring(2);
                 int nomor = Integer.parseInt(idbalita) + 1;
                 String nol = "";
                  if (nomor<10) 
                  {nol = "000";} 
                  else if (nomor<100)
                  {nol = "00";} 
                  else if (nomor<1000)
                  {nol = "0";}
                  else if (nomor<10000)
                  {nol = "";}
                  
                 
                 idblt.setText("IN"+ nol+nomor);
        }
        }
    
     catch (Exception e){ 
        JOptionPane.showMessageDialog(null,"Penomoran Salah" + e);         
    }
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabledatabalita = new javax.swing.JTable();
        lblJum = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        idblt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nmanak = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nmayah = new javax.swing.JTextField();
        nmibu = new javax.swing.JTextField();
        beratbadan = new javax.swing.JTextField();
        panjangbadan = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rw = new javax.swing.JTextField();
        rt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        almt = new javax.swing.JTextArea();
        bubah = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bsimpan = new javax.swing.JButton();
        bhapus = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        radiolaki = new javax.swing.JRadioButton();
        radiopr = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        usia = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        tgllahir = new com.toedter.calendar.JDateChooser();
        b_penblt = new javax.swing.JButton();
        b_penibuhamil = new javax.swing.JButton();
        b_pelblt = new javax.swing.JButton();
        b_pelibuhamil = new javax.swing.JButton();
        b_imun = new javax.swing.JButton();
        b_pgs = new javax.swing.JButton();
        b_laporan = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 0));

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Tabel Data Balita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 14))); // NOI18N

        tabledatabalita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabledatabalita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledatabalitaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabledatabalita);

        lblJum.setText("Jumlah Data");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJum)
                .addGap(19, 19, 19))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJum)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Pendaftaran Ibu Hamil");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("ID Balita");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nama Ayah");

        nmanak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmanakActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Tanggal Lahir");

        panjangbadan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panjangbadanActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alamat", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("RT");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("RW");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Alamat Lengkap");

        almt.setColumns(20);
        almt.setRows(5);
        jScrollPane1.setViewportView(almt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(94, 94, 94))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(89, 89, 89)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rw, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(rt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(rw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bubah.setBackground(new java.awt.Color(255, 255, 255));
        bubah.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ubah.png"))); // NOI18N
        bubah.setText("Ubah");
        bubah.setToolTipText("ubah");
        bubah.setIconTextGap(1);
        bubah.setMargin(new java.awt.Insets(2, 0, 2, 14));
        bubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Nama Anak");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nama Ibu");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Berat Badan");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Panjang Badan");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Kg");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Cm");

        bsimpan.setBackground(new java.awt.Color(255, 255, 255));
        bsimpan.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save (1).png"))); // NOI18N
        bsimpan.setText("Simpan");
        bsimpan.setToolTipText("simpan");
        bsimpan.setIconTextGap(0);
        bsimpan.setMargin(new java.awt.Insets(2, 0, 2, 14));
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bhapus.setBackground(new java.awt.Color(255, 255, 255));
        bhapus.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hapus.png"))); // NOI18N
        bhapus.setText("Hapus");
        bhapus.setToolTipText("hapus");
        bhapus.setIconTextGap(2);
        bhapus.setMargin(new java.awt.Insets(2, 0, 2, 14));
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Jenis Kelamin");

        radiolaki.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(radiolaki);
        radiolaki.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radiolaki.setText("Laki-Laki");
        radiolaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiolakiActionPerformed(evt);
            }
        });

        radiopr.setBackground(new java.awt.Color(153, 204, 255));
        buttonGroup1.add(radiopr);
        radiopr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radiopr.setText("Perempuan");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-female-skin-type-7.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user-male-skin-type-7.png"))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Usia");

        jButton3.setText("hitung");
        jButton3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        bbatal.setBackground(new java.awt.Color(255, 255, 255));
        bbatal.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/batal.png"))); // NOI18N
        bbatal.setText("Batal");
        bbatal.setToolTipText("Batal");
        bbatal.setMargin(new java.awt.Insets(2, 0, 2, 14));
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });

        bkeluar.setBackground(new java.awt.Color(255, 255, 255));
        bkeluar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/keluar2.png"))); // NOI18N
        bkeluar.setText("Keluar");
        bkeluar.setToolTipText("Keluar");
        bkeluar.setMargin(new java.awt.Insets(2, 0, 2, 0));
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(243, 243, 243))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(idblt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(43, 43, 43)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nmanak, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radiopr)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radiolaki))
                                    .addComponent(nmayah, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nmibu, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(panjangbadan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(beratbadan, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(usia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3))
                                    .addComponent(tgllahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(99, 99, 99))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bubah, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bbatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bkeluar))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(idblt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(nmanak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel18)
                            .addComponent(radiopr)
                            .addComponent(radiolaki))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nmayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nmibu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tgllahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(usia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(beratbadan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(panjangbadan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 880, 320));

        b_penblt.setBackground(new java.awt.Color(0, 102, 102));
        b_penblt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_penblt.setForeground(new java.awt.Color(255, 255, 255));
        b_penblt.setText("PENDAFTARAN BALITA");
        b_penblt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_penbltActionPerformed(evt);
            }
        });

        b_penibuhamil.setBackground(new java.awt.Color(0, 102, 102));
        b_penibuhamil.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_penibuhamil.setForeground(new java.awt.Color(255, 255, 255));
        b_penibuhamil.setText("PENDAFTARAN IBU HAMIL");
        b_penibuhamil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_penibuhamilActionPerformed(evt);
            }
        });

        b_pelblt.setBackground(new java.awt.Color(0, 102, 102));
        b_pelblt.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_pelblt.setForeground(new java.awt.Color(255, 255, 255));
        b_pelblt.setText("PELAYANAN BALITA");
        b_pelblt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pelbltActionPerformed(evt);
            }
        });

        b_pelibuhamil.setBackground(new java.awt.Color(0, 102, 102));
        b_pelibuhamil.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_pelibuhamil.setForeground(new java.awt.Color(255, 255, 255));
        b_pelibuhamil.setText("PELAYANAN IBU HAMIL");
        b_pelibuhamil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pelibuhamilActionPerformed(evt);
            }
        });

        b_imun.setBackground(new java.awt.Color(0, 102, 102));
        b_imun.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_imun.setForeground(new java.awt.Color(255, 255, 255));
        b_imun.setText("DATA IMIUSASI");
        b_imun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_imunActionPerformed(evt);
            }
        });

        b_pgs.setBackground(new java.awt.Color(0, 102, 102));
        b_pgs.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_pgs.setForeground(new java.awt.Color(255, 255, 255));
        b_pgs.setText("DATA PETUGAS");
        b_pgs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pgsActionPerformed(evt);
            }
        });

        b_laporan.setBackground(new java.awt.Color(0, 102, 102));
        b_laporan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        b_laporan.setForeground(new java.awt.Color(255, 255, 255));
        b_laporan.setText("LAPORAN");
        b_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_laporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(b_penibuhamil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_penblt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_pelblt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_pelibuhamil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_imun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_pgs, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(b_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(b_penblt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_penibuhamil, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_pelblt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_pelibuhamil, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_imun, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_pgs, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logoposyandu.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("APLIKASI PELAYANAN KESEHATAN");

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("POSYANDU WIJAYA KUSUMA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 860));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nmanakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmanakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmanakActionPerformed

    private void panjangbadanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panjangbadanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panjangbadanActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
int ok = JOptionPane.showConfirmDialog(null,"Hapus","konfirmasi Dialog",JOptionPane.YES_NO_OPTION);
if (ok==0){
        String sql = "delete from pendaftaran_balita where idbalita ='"+idblt.getText()+"'";
try{
    PreparedStatement stat = conn.prepareStatement (sql); 
    stat.executeUpdate();
    JOptionPane.showMessageDialog(null,"Data berhasil dihapus");
    kosong();
    idblt.requestFocus();
}
catch (SQLException e){
    JOptionPane.showMessageDialog(null,"data gagal dihapus" +e);
}
datatable();
        // TODO add your handling code here:
    }      
        // TODO add your handling code here:
    }//GEN-LAST:event_bhapusActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed

SimpleDateFormat sts = new SimpleDateFormat("yyyy-MM-dd"); 
String date = sts.format(tgllahir.getDate());
         
        String jenis = null;
    if (radiolaki.isSelected()){
    jenis = "Laki-Laki";
    }
    else if(radiopr.isSelected()){
    jenis="Perempuan";
    }
        
        String sql = "insert into pendaftaran_balita values (?,?,?,?,?,?,?,?,?,?,?,?)";
try{
    PreparedStatement stat = conn.prepareStatement (sql);
    
    stat.setString (1,idblt.getText());
    stat.setString (2,nmanak.getText());
    stat.setString (3, jenis);
    stat.setString (4,nmayah.getText());
    stat.setString (5,nmibu.getText());
    stat.setString (6,date);
    stat.setString (7,usia.getText());
    stat.setString (8,beratbadan.getText());
    stat.setString (9,panjangbadan.getText());
    stat.setString (10,rt.getText());
    stat.setString (11,rw.getText());
    stat.setString (12,almt.getText());
    
    
    stat.executeUpdate();
    JOptionPane.showMessageDialog(null,"Data berhasil disimpan");
    kosong();
    idblt.requestFocus();
}
catch (SQLException e){
    JOptionPane.showMessageDialog(null,"data gagal disimpan" +e);
}
datatable();        
        // TODO add your handling code here:
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahActionPerformed
String tampilan ="yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String date = String.valueOf(fm.format(tgllahir.getDate()));
        String jenis = null;
    if (radiolaki.isSelected()){
    jenis = "Laki-Laki";
    }
    else if(radiopr.isSelected()){
    jenis="Perempuan";
    }
        
        try{
    String sql = "update pendaftaran_balita set nama_anak=?,jenis_kelamin=?,nama_ayah=?,nama_ibu=?,tanggal_lahir=?,usia=?,berat_badan=?,panjang_badan=?,rt=?,rw=?,alamat_lengkap=? where idbalita ='"+idblt.getText()+"'";
    PreparedStatement stat = conn.prepareStatement (sql);
    
    stat.setString (1,nmanak.getText());
    stat.setString (2, jenis);
    stat.setString (3,nmayah.getText());
    stat.setString (4,nmibu.getText());
    stat.setString (5,date);
    stat.setString (6,usia.getText());
    stat.setString (7,beratbadan.getText());
    stat.setString (8,panjangbadan.getText());
    stat.setString (9,rt.getText());
    stat.setString (10,rw.getText());
    stat.setString (11,almt.getText());
    
    stat.executeUpdate();
    JOptionPane.showMessageDialog(null,"Data berhasil diubah");
    kosong();
    idblt.requestFocus();
}
catch (SQLException e){
    JOptionPane.showMessageDialog(null,"data gagal diubah" +e);
}
datatable();
        // TODO add your handling code here:
    }//GEN-LAST:event_bubahActionPerformed

    private void tabledatabalitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledatabalitaMouseClicked
int bar = tabledatabalita.getSelectedRow();
String a = tabmode.getValueAt(bar,0).toString();
String b = tabmode.getValueAt(bar,1).toString();
String c = tabmode.getValueAt(bar,2).toString();
String d = tabmode.getValueAt(bar,3).toString();
String e = tabmode.getValueAt(bar,4).toString();
String f = tabmode.getValueAt(bar,5).toString();
String g = tabmode.getValueAt(bar,6).toString();
String h = tabmode.getValueAt(bar,7).toString();
String i = tabmode.getValueAt(bar,8).toString();
String j = tabmode.getValueAt(bar,9).toString();
String k = tabmode.getValueAt(bar,10).toString();
String l = tabmode.getValueAt(bar,10).toString();

DateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    try {
        Date Tanggal = sdf.parse(f);
        tgllahir.setDate(Tanggal);
    } catch (ParseException ex) {
        Logger.getLogger(pendaftaran_balita.class.getName()).log(Level.SEVERE, null, ex);
    }


idblt.setText(a);
nmanak.setText(b);
if("Laki-Laki".equals(c)){
    radiolaki.setSelected(true);
}
else {
    radiopr.setSelected(true);
}
nmayah.setText(d);
nmibu.setText(e);


//tgllahir.setDate(null);
usia.setText(g);
beratbadan.setText(h);
panjangbadan.setText(i);
rt.setText(j);
rw.setText(k);
almt.setText(l);


        // TODO add your handling code here:
    }//GEN-LAST:event_tabledatabalitaMouseClicked

    private void radiolakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiolakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiolakiActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Date lahir = tgllahir.getDate();
Date kini = new Date();
int umur = kini.getYear()-lahir.getYear();
usia.setText(String.valueOf(umur));

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tgllahirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgllahirKeyPressed
      // TODO add your handling code here:
    }//GEN-LAST:event_tgllahirKeyPressed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        kosong();
        aktif();
        autonumber();
        // TODO add your handling code here:
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bkeluarActionPerformed

    private void b_penbltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_penbltActionPerformed
new pendaftaran_balita ().setVisible (true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_penbltActionPerformed

    private void b_penibuhamilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_penibuhamilActionPerformed
new pendaftaran_ibuhamil ().setVisible (true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_penibuhamilActionPerformed

    private void b_pelbltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pelbltActionPerformed
new pelayanan_balita ().setVisible (true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_pelbltActionPerformed

    private void b_pelibuhamilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pelibuhamilActionPerformed
new pelayanan_ibuhamil ().setVisible (true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_pelibuhamilActionPerformed

    private void b_imunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_imunActionPerformed
new imunisasi ().setVisible (true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_imunActionPerformed

    private void b_pgsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pgsActionPerformed
new petugas_posyandu ().setVisible (true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_pgsActionPerformed

    private void b_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_laporanActionPerformed
new laporan ().setVisible (true);
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_b_laporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pendaftaran_balita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pendaftaran_balita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pendaftaran_balita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pendaftaran_balita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pendaftaran_balita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea almt;
    private javax.swing.JButton b_imun;
    private javax.swing.JButton b_laporan;
    private javax.swing.JButton b_pelblt;
    private javax.swing.JButton b_pelibuhamil;
    private javax.swing.JButton b_penblt;
    private javax.swing.JButton b_penibuhamil;
    private javax.swing.JButton b_pgs;
    private javax.swing.JButton bbatal;
    private javax.swing.JTextField beratbadan;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField idblt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblJum;
    private javax.swing.JTextField nmanak;
    private javax.swing.JTextField nmayah;
    private javax.swing.JTextField nmibu;
    private javax.swing.JTextField panjangbadan;
    private javax.swing.JRadioButton radiolaki;
    private javax.swing.JRadioButton radiopr;
    private javax.swing.JTextField rt;
    private javax.swing.JTextField rw;
    private javax.swing.JTable tabledatabalita;
    private com.toedter.calendar.JDateChooser tgllahir;
    private javax.swing.JTextField usia;
    // End of variables declaration//GEN-END:variables
}
