/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package posyandu;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import posyandu.pelayanan_ibuhamil;
import koneksi.koneksi; 
/**
 *
 * @author Adji
 */
public class popup_databalita extends javax.swing.JFrame {
private Connection conn = new koneksi ().connect();
private DefaultTableModel tabmode;

public pelayanan_balita balita = null;

    /**
     * Creates new form popup_databalita
     */
    public popup_databalita() {
        initComponents();
        datatable();
    }
    
    protected void datatable(){
   Object[]Baris ={"idbalita","nama anak","jenis kelamin","nama ayah","nama ibu","tanggal lahir","Usia","berat badan","panjang badan","rt","rw","alamat"};
           tabmode = new DefaultTableModel(null, Baris);
            String cariitem=txtcari.getText(); 
            
            try{
                String sql = "SELECT * FROM pendaftaran_balita where idbalita like '%"+cariitem+"%' or nama_anak like '%"+cariitem+"%' order by idbalita asc";
             Statement stat = conn.createStatement();
             ResultSet hasil = stat.executeQuery(sql);
             while (hasil.next()){
                  tabmode.addRow(new Object[]{ 
                      hasil.getString(1),
                      hasil.getString(2),
                      hasil.getString(3),
                      hasil.getString(4),
                      hasil.getString(5), 
                      hasil.getString(6),
                      hasil.getString(7),
                      hasil.getString(8),
                      hasil.getString(9),
                      hasil.getString(10),
                      hasil.getString(11),
                      hasil.getString(12)
                  });
             }
              tablepopupdatabalita.setModel(tabmode); 
                  }
            catch(Exception e){
                 JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e); 
             } 
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcari = new javax.swing.JTextField();
        bcari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepopupdatabalita = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        bcari.setText("cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        tablepopupdatabalita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablepopupdatabalita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepopupdatabalitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablepopupdatabalita);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bcari)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariKeyPressed

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        datatable();
        // TODO add your handling code here:
    }//GEN-LAST:event_bcariActionPerformed

    private void tablepopupdatabalitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepopupdatabalitaMouseClicked
         int tabeldatabalita = tablepopupdatabalita.getSelectedRow();
        balita.id_balita = tablepopupdatabalita.getValueAt(tabeldatabalita, 0).toString();
        balita.nama_anak = tablepopupdatabalita.getValueAt(tabeldatabalita, 1).toString();
        balita.jenis_kelamin = tablepopupdatabalita.getValueAt(tabeldatabalita, 2).toString();
        balita.nama_ayah = tablepopupdatabalita.getValueAt(tabeldatabalita, 3).toString();
        balita.nama_ibu = tablepopupdatabalita.getValueAt(tabeldatabalita, 4).toString();
        balita.tanggal_lahir = tablepopupdatabalita.getValueAt(tabeldatabalita, 5).toString();
        balita.usia_anak = tablepopupdatabalita.getValueAt(tabeldatabalita, 6).toString();
        balita.berat_badan = tablepopupdatabalita.getValueAt(tabeldatabalita, 7).toString();
        balita.panjang_badan = tablepopupdatabalita.getValueAt(tabeldatabalita, 8).toString();
        balita.rt = tablepopupdatabalita.getValueAt(tabeldatabalita, 9).toString();
        balita.rw = tablepopupdatabalita.getValueAt(tabeldatabalita, 10).toString();
        balita.alamat_lengkap = tablepopupdatabalita.getValueAt(tabeldatabalita, 11).toString();
        balita.itemTerpilih3();
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_tablepopupdatabalitaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popup_databalita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popup_databalita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popup_databalita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popup_databalita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popup_databalita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcari;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablepopupdatabalita;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
